@extends('layouts.app')

@section('content')
    <section class="about w-full yellowbg">
        <div>
            <center>
                <h1 class='text-xxl font-bold fontBlont'>
                    {{ __('messages.Cookies') }}
                </h1>
            </center>

        </div>
    </section>

<br>
<br>
<br>
    <section class="section w-full">
        <strong>Updated at 2022-12-08</strong>
        <br>
        <br>
        <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Definitions and key terms</span></p>
            <p></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly defined as:</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Cookie:&nbsp;small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, and remember information about you such as your language preference or login information.</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Sawtru Boost Website , that is responsible for your information under this Cookie Policy.</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Device:&nbsp;any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Sawtru Boost Website&nbsp; and use the services.</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Service: refers to the service provided by Sawtru Boost Website&nbsp; as described in the relative terms (if available) and on this platform.</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Third-party service:&nbsp;refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Website: Sawtru Boost Website, which can be accessed via this URL: https://sawtruboost.com</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-You: a person or entity that is registered with Sawtru Boost Website&nbsp; to use the Services.</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Introduction</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">This Cookie Policy explains how Sawtru Boost Website&nbsp; and its affiliates (collectively "Sawtru Boost Website ", "we", "us", and "ours"), use cookies and similar technologies to recognize you when you visit our website, including without limitation https://sawtruboost.com and any related URLs, mobile or localized versions and related domains / sub-domains ("Websites"). It explains what these technologies are and why we use them, as well as the choices for how to control them.</span></p>
            <br />
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">What is a cookie?</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, and remember information about you such as your language preference or login information. They're completely safe and can't be used to run programs or deliver viruses to your device.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Why do we use cookies?</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">We use first party and/or third party cookies on our website for various purposes such as:</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-To facilitate the operation and functionality of our website;</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-To improve your experience of our website and make navigating around them quicker and easier;</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you;</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-To analyze how our website is used and how best we can customize it;</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-To identify future prospects and personalize marketing and sales interactions with it;</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-To facilitate the tailoring of online advertising to your interests.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">What type of cookies does Sawtru Boost Website&nbsp; use?</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you’re visiting are called “first party cookies”.</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Strictly Necessary cookies are necessary for our website to function and cannot be switched off in our systems. They are essential in order to enable you to navigate around the website and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our website.</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">We use the following types of cookies in our website:</span></p>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Errors and Omissions Disclaimer</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Sawtru Boost Website&nbsp; is not responsible for any content, code or any other imprecision.</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Sawtru Boost Website&nbsp; does not provide warranties or guarantees.</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">In no event shall Sawtru Boost Website&nbsp; be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. Sawtru Boost Website&nbsp; reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">General Disclaimer</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">The Sawtru Boost Website&nbsp; Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Sawtru Boost Website&nbsp; is a distributor and not a publisher of the content supplied by third parties; as such, Sawtru Boost Website&nbsp; exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Sawtru Boost Website&nbsp; Service. Without limiting the foregoing, Sawtru Boost Website&nbsp; specifically disclaims all warranties and representations in any content transmitted on or in connection with the Sawtru Boost Website&nbsp; Service or on sites that may appear as links on the Sawtru Boost Website&nbsp; Service, or in the products provided as a part of, or otherwise in connection with, the Sawtru Boost Website&nbsp; Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Sawtru Boost Website&nbsp; or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Sawtru Boost Website&nbsp; does not warrant that the Sawtru Boost Website&nbsp; Service will be uninterrupted, uncorrupted, timely, or error-free.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Essential Cookies</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">We use essential cookies to make our website work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn't be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.</span></p>
            <br />
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Performance and Functionality Cookies</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">These cookies are used to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Marketing Cookies</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">These account-based marketing cookies enable us to identify future prospects and personalize sales and marketing interactions with them.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Analytics and Customization Cookies</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">These cookies collect information that is used to help us understand how our website is being used or how effective our marketing campaigns are, or to help us customize our website for you.</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">We use cookies served by Google Analytics to collect limited data directly from end-user browsers to enable us to better understand your use of our website. Further information on how Google collects and uses this data can be found at:&nbsp;https://www.google.com/policies/privacy/partners/. You can opt-out of all Google supported analytics on our Websites by visiting:&nbsp;https://tools.google.com/dlpage/gaoptout.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Social Media Cookies</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">These cookies are used when you share information using a social media sharing button or “like” button on our Site or you link your account or engage with our content on or through a social networking website such as Facebook, Twitter or Google+. The social network will record that you have done this. These cookies may also include certain code that has been placed on the platform to help track conversions from ads, optimize ads based on collected data, build targeted audiences for future ads, and remarket to qualified users who have already taken certain action on the platform.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Third Party Cookies</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Some cookies that have been set on our website are not set on a first party basis by Sawtru Boost Website . The Websites can be embedded with content from third parties to serve advertising. These third party service providers may set their own cookies on your web browser. Third party service providers control many of the performance and functionality, advertising, marketing and analytics cookies described above. We do not control the use of these third party cookies as cookies can only be accessed by the third party that originally set them.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">How can you manage cookies?</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Most browsers allow you to control cookies through their 'settings' preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Browser manufacturers provide help pages relating to cookie management in their products. Please see below for more information.</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Google Chrome</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Internet Explorer</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Mozilla Firefox</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Safari (Desktop)</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Safari (Mobile)</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Android Browser</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Opera</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;&nbsp;-Opera Mobile</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Blocking and disabling cookies and similar technologies</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Changes To Our Cookie Policy</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any updated Cookie Policy, you can delete your account.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Your Consent</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.</span></p>
            <br />
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:13.999999999999998pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Contact Us</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">Don't hesitate to contact us if you have any questions regarding our Cookie Policy.</span></p>
            <br />
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;-Via Email:&nbsp; info@sawtruboost.com</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;-Via Phone Number:&nbsp; +90 506 467 79 87</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;-Via this Link:&nbsp; https://sawtruboost.com/boostnow</span></p>
            <p dir="ltr" style="line-height:1.38"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap">&nbsp;-Via this Address: Akevler, VENUS RESIDANCE, 1066. Sk. NO:2 D:KAT:4 DAIRE:30, 34513 Esenyurt/İstanbul</span></p>
            <br />
            <br />
            <br />
            </p>



    </section>



    @push('custom-scripts')
        <script type="module" src="{{ URL::asset('js/home.js') }}"></script>
    @endpush
@endsection
